import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/someone.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/icons'
import HireMe from '@/components/HireMe'
import { motion } from "framer-motion"
import coffee from "../../public/images/svgs/coffee.png"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={profilePic} alt="def not me" className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>

            <AnimatedText text="Turning Data Into Doing...</>" className='!text-6xl !text-left'/>
            
            <p className='my-4 text-base font-medium'> 
              As a skilled full-stack developer and ML Enthusiast, I am dedicated to turning ideas into innovative web applications.
              Explore my latest projects, showcasing my expertise in Web development and ML.
            </p>
            <motion.div className='flex items-center self-start mt-2'        
            
            //Try something later

            >
              <Link href="/Resume.pdf"
              target={"_blank"} className='flex items-center bg-dark text-light p-2.5 px-6
              rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
              border-2 border-solid border-transparent hover:border-dark
              '
              download={true}
              >Resume <LinkArrow className={"w-6 ml-1"}/> </Link>
              <Link href="mailto:aayushkumr25@gmail.com"
              target={'_blank'} className='mx-3 flex items-center bg-dark text-light p-2.5 px-5
              rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
              border-2 border-solid border-transparent hover:border-dark
              '
              >Contact Me</Link>
            </motion.div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-1 bottom-1 inline-block w-15'>
          <a href="https://www.buymeacoffee.com/aayushkumrS?new=1">
            <Image src={coffee} alt="Buymecoffee" className='w-full h-auto' />
          </a>
        </div>
      </main>
    </>
  )
}
